voice_group title
	voice_keysplit voicegroup_piano_keysplit, keysplit_piano
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_glockenspiel, 255, 165, 51, 242
	voice_keysplit voicegroup_piano_keysplit, keysplit_piano
	voice_keysplit voicegroup_piano_keysplit, keysplit_piano
	voice_keysplit voicegroup_piano_keysplit, keysplit_piano
	voice_keysplit voicegroup_piano_keysplit, keysplit_piano
	voice_keysplit voicegroup_piano_keysplit, keysplit_piano
	voice_keysplit voicegroup_piano_keysplit, keysplit_piano
	voice_keysplit voicegroup_piano_keysplit, keysplit_piano
	voice_keysplit voicegroup_piano_keysplit, keysplit_piano
	voice_keysplit voicegroup_strings_keysplit, keysplit_strings
	voice_keysplit voicegroup_tuba_keysplit, keysplit_tuba
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_flute, 255, 0, 255, 165
