voice_group vs_trainer
	voice_keysplit_all voicegroup_rs_drumset
	voice_keysplit voicegroup_piano_keysplit, keysplit_piano
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_organ2, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_fingered_bass, 255, 253, 0, 149
	voice_keysplit voicegroup_strings_keysplit, keysplit_strings
	voice_keysplit voicegroup_trumpet_keysplit, keysplit_trumpet
	voice_keysplit voicegroup_french_horn_keysplit, keysplit_french_horn
	
